name: Actualizar Calendario Mundial 2026
on:
  schedule:
    - cron: '0 0 * * 1' # Cada lunes
  workflow_dispatch: # Botón para darle "Play" a mano

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          pip install playwright aiohttp
          playwright install chromium

      - name: Ejecutar Scraper
        run: python main.py

      - name: Guardar JSON en el Repo
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add eventos_2026.json
          git commit -m "📅 Actualización automática datos World Athletics" || exit 0
          git push